apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: newservice
  name: newservice
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: newservice
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.34.0 (HEAD)
      labels:
        io.kompose.service: newservice
    spec:
      containers:
        - image: newservice
          name: newservice
          imagePullPolicy: Never
          ports:
            - containerPort: 3005
              protocol: TCP
      restartPolicy: Always
