apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: orderconfirmation
  name: orderconfirmation
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: orderconfirmation
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.34.0 (HEAD)
      labels:
        io.kompose.service: orderconfirmation
    spec:
      containers:
        - image: orderconfirmation
          name: orderconfirmation
          imagePullPolicy: Never
          ports:
            - containerPort: 3003
              protocol: TCP
      restartPolicy: Always
